name: Release to Pypi

# Run on a published release and push to Pypi
on:
  release:
    types: [published]

jobs:
  build_dist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip wheel
          python3 -m pip install .

      - name: Build dist
        run: python setup.py sdist --formats=gztar

      - name: Build wheel
        run: python3 setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  pypi-publish:
    needs: [build_dist]
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      # retrieve your distributions here
      - uses: actions/download-artifact@v2
        with:
            name: artifact
            path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
